from __future__ import annotations

from dataclasses import dataclass, field

from vllm.v1.request import Request


@dataclass
class BeamState:
    """State for a single beam hypothesis."""

    request: Request
    score: float = 0.0
    # Output tokens generated by this beam (tracked separately from
    # request._output_token_ids so we can reconstruct the full sequence
    # after beam search completes).
    token_ids: list[int] = field(default_factory=list)
    # Whether this beam has hit a stop condition.
    finished: bool = False


@dataclass
class BeamGroup:
    """Tracks all beams for a single user request."""

    original_request_id: str
    # The original request object (never scheduled directly).
    original_request: Request
    beam_width: int
    length_penalty: float = 1.0

    # beam_req_id -> BeamState
    active_beams: dict[str, BeamState] = field(default_factory=dict)
    # Best completed beam so far (for early stopping).
    best_completed: BeamState | None = None

    # Generation counter for creating unique beam IDs on fork.
    _beam_counter: int = 0

    def next_beam_id(self) -> str:
        beam_id = f"{self.original_request_id}:beam:{self._beam_counter}"
        self._beam_counter += 1
        return beam_id

    @property
    def num_active(self) -> int:
        return sum(1 for b in self.active_beams.values() if not b.finished)

    @property
    def all_finished(self) -> bool:
        return all(b.finished for b in self.active_beams.values())

    def normalized_score(self, score: float, length: int) -> float:
        """Apply length normalization to a beam score.

        Uses the Wu et al. (2016) length penalty:
            score / ((5 + length) / 6) ^ length_penalty
        """
        if self.length_penalty == 0.0:
            return score
        penalty = ((5.0 + length) / 6.0) ** self.length_penalty
        return score / penalty

    def can_early_stop(self) -> bool:
        """Check if we can stop early.

        True when the best completed beam's normalized score is better than
        the best possible score of any active beam (i.e., their current
        score, since log-probs are <= 0 and can only decrease).
        """
        if self.best_completed is None:
            return False

        best_completed_score = self.normalized_score(
            self.best_completed.score,
            len(self.best_completed.token_ids),
        )
        for beam in self.active_beams.values():
            if beam.finished:
                continue
            # Best possible score for this beam is its current score
            # (adding more tokens can only decrease it since logprobs <= 0).
            best_possible = self.normalized_score(
                beam.score,
                len(beam.token_ids),
            )
            if best_possible > best_completed_score:
                return False
        return True
